# Generated by Django 4.1.7 on 2023-04-09 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Class", "0001_initial"),
        ("main", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("school", "0001_initial"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marks",
            name="class_subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="school.classsubject"
            ),
        ),
        migrations.AddField(
            model_name="marks",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="student.student"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_subjects",
                to="main.employee",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Class.class"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="main_users", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.schools",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text='Specific permissions for this user.Note: This only affects permissions checked by the "has_permission" method on models.',
                related_name="main_users",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
