# Generated by Django 4.1.7 on 2023-04-01 21:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclasses",
            name="pass_percentage",
            field=models.FloatField(
                default=33.3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="classes",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="schools",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="student",
            name="father_cnic",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="student",
            name="mobile",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_cnic",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_position", models.PositiveIntegerField(blank=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.student"
                    ),
                ),
            ],
        ),
    ]
