# Generated by Django 4.1.7 on 2023-04-08 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
        ("student", "0001_initial"),
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="selected_school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="school.schools"
            ),
        ),
        migrations.AddField(
            model_name="marks",
            name="class_subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="school.classsubject"
            ),
        ),
        migrations.AddField(
            model_name="marks",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="student.student"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="school.schools"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
