# Generated by Django 4.1.7 on 2023-04-02 00:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="name",
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schoolclasses",
            name="pass_percentage",
            field=models.FloatField(
                default=33.3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="classes",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="schools",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="student",
            name="father_cnic",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="student",
            name="mobile",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_cnic",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_changes", models.BooleanField(default=False)),
                ("batch_marks_changes", models.BooleanField(default=False)),
                ("single_marks_changes", models.BooleanField(default=False)),
                ("subject_changes", models.BooleanField(default=True)),
                ("marks_lock_changes", models.BooleanField(default=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.employee"
                    ),
                ),
                (
                    "selected_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.classes"
                    ),
                ),
                (
                    "selected_school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.schools"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_position", models.PositiveIntegerField(blank=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.student"
                    ),
                ),
            ],
        ),
    ]
