# Generated by Django 4.1.7 on 2023-04-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_employee_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schools",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
