# Generated by Django 4.1.7 on 2023-04-03 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_schools_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="schools",
            name="employees",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.employee",
            ),
        ),
    ]
