# Generated by Django 4.1.7 on 2023-04-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_schools_employees_alter_employee_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="schools",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
