# Generated by Django 4.1.7 on 2023-04-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
        ("main", "0007_schools_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marks",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="student.student"
            ),
        ),
        migrations.DeleteModel(
            name="Position",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
