# Generated by Django 4.1.7 on 2023-04-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_marks_student_delete_position_delete_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classsubject",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="classsubject",
            name="school_class",
        ),
        migrations.RemoveField(
            model_name="classsubject",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="schoolclasses",
            name="classes",
        ),
        migrations.RemoveField(
            model_name="schoolclasses",
            name="school",
        ),
        migrations.RemoveField(
            model_name="schools",
            name="classes",
        ),
    ]
