# Generated by Django 4.1.7 on 2023-04-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
        ("main", "0009_remove_classsubject_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="school.schools"
            ),
        ),
        migrations.AlterField(
            model_name="marks",
            name="class_subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="school.classsubject"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="selected_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="school.classes"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="selected_school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="school.schools"
            ),
        ),
        migrations.DeleteModel(
            name="Classes",
        ),
        migrations.DeleteModel(
            name="ClassSubject",
        ),
        migrations.DeleteModel(
            name="SchoolClasses",
        ),
        migrations.DeleteModel(
            name="Schools",
        ),
    ]
