# Generated by Django 4.1.7 on 2023-04-09 23:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("roll_no", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("father_name", models.CharField(max_length=30)),
                ("date_of_birth", models.DateField(blank=True, default="1900-01-01")),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                (
                    "admission_no",
                    models.IntegerField(
                        default=models.IntegerField(primary_key=True, serialize=False),
                        unique=True,
                    ),
                ),
                ("admission_date", models.DateField(default=datetime.datetime.now)),
                ("student_cnic", models.CharField(max_length=15, unique=True)),
                ("father_cnic", models.CharField(max_length=15)),
                ("mobile", models.CharField(max_length=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Struck off", "Struck off"),
                            ("Graduated", "Graduated"),
                        ],
                        default="Active",
                        max_length=10,
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.schoolclasses",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.schoolclasses",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_position", models.PositiveIntegerField(blank=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
            ],
        ),
    ]
