# Generated by Django 4.1.7 on 2023-04-03 15:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("roll_no", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("dob", models.DateField(blank=True, default="01/01/1990")),
                (
                    "admission_no",
                    models.IntegerField(
                        default=models.IntegerField(primary_key=True, serialize=False)
                    ),
                ),
                ("admission_date", models.DateField(default=datetime.datetime.now)),
                ("student_cnic", models.CharField(max_length=15)),
                ("father_cnic", models.CharField(max_length=15)),
                ("mobile", models.CharField(max_length=12)),
                ("class_position", models.PositiveIntegerField(blank=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_position", models.PositiveIntegerField(blank=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
            ],
        ),
    ]
