# Generated by Django 4.1.7 on 2023-04-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_remove_student_class_position_alter_student_dob"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="dob",
            new_name="date_of_birth",
        ),
    ]
