# Generated by Django 4.1.7 on 2023-04-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0008_alter_student_admission_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="active",
        ),
        migrations.AddField(
            model_name="student",
            name="father_name",
            field=models.CharField(default="Does not exist", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="M", max_length=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[("A", "Active"), ("S", "Struck off"), ("G", "Graduated")],
                default="A",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="student_cnic",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
