# Generated by Django 4.1.7 on 2023-04-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0009_remove_student_active_student_father_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Struck off", "Struck off"),
                    ("Graduated", "Graduated"),
                ],
                max_length=10,
            ),
        ),
    ]
